"""Changed back to activity_plan within specifications

Revision ID: 95e1b029b252
Revises: a7b167324eef
Create Date: 2024-10-14 17:48:57.528439

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '95e1b029b252'
down_revision: Union[str, None] = 'a7b167324eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_column('activity_plan')

    # ### end Alembic commands ###
