"""Add EduSpecification and EduProjectStates tables

Revision ID: a7b167324eef
Revises: fff81c0a0076
Create Date: 2024-10-14 15:51:01.078827

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7b167324eef'
down_revision: Union[str, None] = 'fff81c0a0076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_column('activity_plan')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_plan', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
