"""Add activity_plan to specifications

Revision ID: a972319e45f0
Revises: c8905d4ce784
Create Date: 2024-10-13 17:39:31.613718

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a972319e45f0'
down_revision: Union[str, None] = 'c8905d4ce784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_column('activity_plan')

    # ### end Alembic commands ###
