"""Add EduSpecification and EduProjectStates tables

Revision ID: fff81c0a0076
Revises: a972319e45f0
Create Date: 2024-10-14 15:32:21.210572

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fff81c0a0076'
down_revision: Union[str, None] = 'a972319e45f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
